// pages/_app.tsx

import type { AppProps } from 'next/app'
import { Metadata } from 'next'
import { Inter } from 'next/font/google'
import '../app/globals.css'

import Navbar from '@/components/Navbar'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

function MyApp({ Component, pageProps }: AppProps) {
  return (
    <>
      <Navbar />
      <Component {...pageProps} />
    </>
  )
}

export default MyApp
